"""crear_esquema_inicial_cuidandopeluditos

Revision ID: e8a513e6a950
Revises: 
Create Date: 2026-09-25 18:13:45.050005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a513e6a950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('provincia', sa.String(length=60), nullable=False),
    sa.Column('localidad', sa.String(length=60), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_localidad'), ['localidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_provincia'), ['provincia'], unique=False)

    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dueno_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=20), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('tamano', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cuidados_especiales', sa.Text(), nullable=True),
    sa.Column('contacto_veterinario', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mascotas_dueno_id'), ['dueno_id'], unique=False)

    op.create_table('perfiles_cuidadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.Column('admite_perros', sa.Boolean(), nullable=False),
    sa.Column('admite_gatos', sa.Boolean(), nullable=False),
    sa.Column('condiciones_convivencia', sa.Text(), nullable=True),
    sa.Column('tarifa_diaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['perfiles_cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disponibilidades_cuidador_id'), ['cuidador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disponibilidades_fecha_desde'), ['fecha_desde'], unique=False)
        batch_op.create_index(batch_op.f('ix_disponibilidades_fecha_hasta'), ['fecha_hasta'], unique=False)

    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dueno_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total_mascotas', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=100), nullable=False),
    sa.Column('veterinario_emergencia', sa.String(length=100), nullable=True),
    sa.Column('autorizacion_urgencia', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['perfiles_cuidadores.id'], ),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_cuidador_id'), ['cuidador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_dueno_id'), ['dueno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_fecha_desde'), ['fecha_desde'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_fecha_hasta'), ['fecha_hasta'], unique=False)

    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('reportado_por_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('medidas_tomadas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reportado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('nombre_snapshot', sa.String(length=50), nullable=False),
    sa.Column('especie_snapshot', sa.String(length=20), nullable=False),
    sa.Column('cuidados_snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valoraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('dueno_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('puntaje >= 1 AND puntaje <= 5', name='chk_puntaje_rango'),
    sa.ForeignKeyConstraint(['cuidador_id'], ['perfiles_cuidadores.id'], ),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoraciones')
    op.drop_table('solicitudes_mascotas')
    op.drop_table('incidencias')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_fecha_hasta'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_fecha_desde'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_estado'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_dueno_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_cuidador_id'))

    op.drop_table('solicitudes')
    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disponibilidades_fecha_hasta'))
        batch_op.drop_index(batch_op.f('ix_disponibilidades_fecha_desde'))
        batch_op.drop_index(batch_op.f('ix_disponibilidades_cuidador_id'))

    op.drop_table('disponibilidades')
    op.drop_table('perfiles_cuidadores')
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mascotas_dueno_id'))

    op.drop_table('mascotas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_provincia'))
        batch_op.drop_index(batch_op.f('ix_usuarios_localidad'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
